load("@io_bazel_rules_go//go:def.bzl", "go_library", "go_test")

go_library(
    name = "debug",
    srcs = [
        "adapter.go",
        "breakpoint.go",
        "clone.go",
        "dataflow.go",
        "debug.go",
        "event.go",
        "frame.go",
    ],
    importpath = "github.com/tedks/CodingGame/internal/debug",
    visibility = ["//visibility:public"],
)

go_test(
    name = "debug_test",
    srcs = ["debug_test.go"],
    embed = [":debug"],
)
