load("@io_bazel_rules_go//go:def.bzl", "go_library", "go_test")

go_library(
    name = "unit",
    srcs = ["unit.go"],
    importpath = "github.com/tedks/CodingGame/internal/unit",
    visibility = ["//visibility:public"],
)

go_test(
    name = "unit_test",
    srcs = ["unit_test.go"],
    embed = [":unit"],
)
