load("@io_bazel_rules_go//go:def.bzl", "go_library", "go_test")

go_library(
    name = "mapview",
    srcs = [
        "layout.go",
        "mapview.go",
    ],
    importpath = "github.com/tedks/CodingGame/internal/mapview",
    visibility = ["//visibility:public"],
    deps = [
        "//internal/belt",
        "//internal/connection",
        "//internal/tile",
        "@com_github_hajimehoshi_ebiten_v2//:ebiten",
        "@com_github_hajimehoshi_ebiten_v2//ebitenutil",
        "@com_github_hajimehoshi_ebiten_v2//vector",
    ],
)

go_test(
    name = "mapview_test",
    srcs = [
        "layout_test.go",
        "mapview_test.go",
    ],
    embed = [":mapview"],
)
